baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Sharon Klinkenberg"
# theme = "hugo-strata-theme"
# theme = "hugo-academic"
# theme = "Mainroad"
theme = "hugo-lithium-theme"
# theme = "startbootstrap-clean-blog"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ShKlinkenberg"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/ShKlinkenberg"

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.10.0"
    highlightCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

